### PR TITLE
Fix#193

### LINKED ISSUE #193: Call to undefined method OCA\\OpenCloudMesh\\ShareeSearchPlugin::splitUserRemote()
```
{"reqId":"ZIM2cxk2-kDZ8nnVIEnQswAAAAA","level":3,"time":"09\/Jun\/2023:16:25:56","remoteAddr":"10.234.0.3","user":"surfsara","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=Test&perPage=200&itemType=folder","message":"Error: Call to undefined method OCA\\OpenCloudMesh\\ShareeSearchPlugin::splitUserRemote() at \/var\/www\/owncloud\/apps\/opencloudmesh\/lib\/ShareeSearchPlugin.php#88"}
{"reqId":"ZIM2d9TTOdE0nhXrtKxIjgAAAAk","level":3,"time":"09\/Jun\/2023:16:26:00","remoteAddr":"10.234.2.58","user":"surfsara","app":"no app in context","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"Failed to notify remote server of mixed group share, panic (Sharing Photos failed, could not find TestGroup (uniharderwijk_surfdrive_test) (SRAM CO), maybe the server is currently unreachable.)"}
```

### PR DESCRIPTION
**Pull request by navid-shokri**

### CODE REVIEW

File: opencloudmesh/lib/ShareeSearchPlugin.php [hunk 1]
```diff
@@ -124,14 +124,7 @@ public function search($search) {
...
 							'server' => $serverUrl,
-						],
-						'label' =>  $contact['FN'],
-						'value' => [
-							'shareType' => Share::SHARE_TYPE_REMOTE_GROUP,
-							'shareWith' => $cloudId,
-							'server' => $serverUrl,
-						],
-					];
+						]];
```
Comment (yasharpm) [inline opencloudmesh/lib/ShareeSearchPlugin.php:129]: Why remove these lines?

File: opencloudmesh/tests/ShareeSearchPluginTest.php [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    public function test_search_when_contact_manager_has_CLOUD_item(){
+
+        $this->contactsManager->expects($this->once())
+            ->method("search")->willReturn([
+                [
+                    "CLOUD"=>"someCloudId@someCloud.com", 
+                    "uid" =>"someCloudId",
+                    "FN" => "someone"
+                ]]);
+        $this->shareeSearchPluguin = new ShareeSearchPlugin($this->config, $this->userManager,
```
Comment (yasharpm) [inline opencloudmesh/tests/ShareeSearchPluginTest.php]: I think `shareeSearchPlugin` should be created on setup.

**Review by yasharpm — CHANGES_REQUESTED** [review]
Maybe it's a good idea to have another test case for when the user manager search does not find any matches, but we still expect 2 results for `REMOTE` and `REMOTE_GROUP`.

**Comment by navid-shokri** [comment]
> Maybe it's a good idea to have another test case for when the user manager search does not find any matches, but we still expect 2 results for `REMOTE` and `REMOTE_GROUP`.

so the Issue was about a bug fix and not full test coverage but I will add that test

File: opencloudmesh/lib/ShareeSearchPlugin.php (hunk 1 above)
Comment (navid-shokri) [reply opencloudmesh/lib/ShareeSearchPlugin.php:129]: because when you find the searched phrase in some contacts metadata it should be a user (person), not a group.
it is unusual to save a group as a contact. right?

Comment (yasharpm) [reply opencloudmesh/lib/ShareeSearchPlugin.php:129]: What if there is a user called scientist AND there is a group called scientist?
Kindly, please do not mark a conversation as resolved while I have not responded yet. :-)

Comment (navid-shokri) [reply opencloudmesh/lib/ShareeSearchPlugin.php:129]: just scientist? The scientist is a local user/group and the shareeSearchPlugin is in the circuit when the search has some @ to indicate the user is remote.

Comment (navid-shokri) [reply opencloudmesh/lib/ShareeSearchPlugin.php:129]: I will describe the workflow to explain the system: 
1- If you type a search phrase without any @ the code will jump from running any logic and return an empty array. 
2- if you send a Search phrase that contains at least one @:
   2-1- code search in all contacts that have the same CloudId `CLOUD` in their Contact. 
   2-2- code search in all contacts that have the same other property like `FN` in their Contact. 
   2-3- if the above Items have no result to provide code will generate two results. first one for USER and second one For group.

**Review by yasharpm — APPROVED** [review]
